### ISSUE TITLE
Deploy on Coolify (VPS) - AI not working

### ISSUE THREAD

**Issue by finnicius** [briefercloud/briefer#263] opened 2024-11-27 10:43 UTC
Hello, team,

I've deployed Briefer using Coolify on a private VPS. I followed the process using the provided image and manually added the three required volumes.

*(For reference, Coolify is a self-hostable platform-as-a-service (PaaS) that simplifies app deployment and management, similar to tools like Heroku or Dokku.)*

Everything seems to be running smoothly, except for one issue: the AI functionality doesn't appear to be working. When I type a command (such as "Edit with AI" or "Fix with AI"), the component briefly flashes, but no response is returned.

Additionally, I’d like to suggest adding Briefer as a single-click deploy template for Coolify. This could make the deployment process much easier for other users and increase adoption. Coolify provides instructions for contributing services as templates here: [https://coolify.io/docs/contribute/service/](https://coolify.io/docs/contribute/service/).

Let me know if you have any insights about the AI issue or thoughts on the Coolify template suggestion. 

Thanks!

**Comment by lucasfcosta** [comment] 2024-11-28 18:26
Thanks for the feedback Finnicius! This makes total sense.

With regards to the Edit and Fix with AI features, they should not be enabled until you add an Open AI API Key.

Did you add one in the "Settings" page and it still didn't work?

**Comment by finnicius** [comment] 2024-11-29 02:55
Hi, Lucas!

Yes, I have properly added the OpenAI key before testing the AI features.

**Comment by sl-NZ** [comment] 2024-12-10 10:02
Seeing a similar issue on docker deploy on a EC2, connection refused error trying to connect to 127.0.0.1:8000 from briefer container logs.

**Comment by vieiralucas** [comment] 2024-12-13 14:15
@sl-NZ has found the root cause of this problem and opened this issue #293.

Closing this one in favor of #293

**Closed by vieiralucas** 2024-12-13 14:15 UTC

**Comment by arthrod** [comment] 2025-02-16 12:02
@finnicius como vc conseguiu?
