### ISSUE TITLE
[feature] Add functionality to export data in .briefer format

### ISSUE THREAD

**Issue by WallPasq** [briefercloud/briefer#74] opened 2024-09-16 23:57 UTC
Hi,

I have been working with the briefer application and wanted to share some findings and suggestions regarding data backups.

## Testing Data Backup with pg_dump
I tested using pg_dump for backing up the data, and I'm pleased to report that it works very well. Here are the commands I used to create a backup, restore it, and verify that everything functions as expected:

### To create a backup
```shell
docker exec -t briefer pg_dump -U postgres --data-only briefer > briefer.sql
``` 

### To remove all data from briefer and test if the backup works
```shell
docker rm briefer
docker volume rm briefer_briefer_data briefer_jupyter_data briefer_psql_data
``` 

### To restore the backup
```shell
docker cp ./briefer.sql briefer:/tmp/briefer.sql
docker exec -t briefer psql -U postgres -d briefer -f /tmp/briefer.sql
``` 

Note: I have not yet checked if there are any conflicts when importing different backups. Once I test scenarios involving multiple backups, I'll provide further feedback.

## Feature Suggestion
Based on this experience, I would like to suggest adding functionality to the briefer application that allows users to export data directly in a .briefer format. This feature would simplify the backup and restore process, especially for users who may not be familiar with PostgreSQL commands or Docker operations.

## Benefits of This Feature:
User-Friendly: Simplifies the backup process for end-users.
Consistency: Ensures that data backups are consistent and compatible with the application's requirements.
Accessibility: Makes it easier for users to share data or migrate between different instances of the application.
I believe this feature would enhance the usability of briefer and make data management more straightforward for all users.

Thank you for considering this suggestion. Please let me know if there's any additional information I can provide or if there's anything I can do to help implement this feature.

Best regards,

Wallacy Nerio

**Comment by lucasfcosta** [comment] 2024-09-17 22:36
Love this issue, it's probably a duplicate of #55 for now! I'll close it so it's easier for us to keep track of everything that's going on, but thanks so much for adding it @WallPasq!

**Closed by lucasfcosta** 2024-09-17 22:36 UTC
